version: '2'

services:
  backend-PRPORTS:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nanocloud/backend
    volumes:
      - static-PRPORTS:/opt/back/assets/dist
    env_file:
      - config.env
    networks:
      - nanocloud
    depends_on:
      - postgres-PRPORTS
    restart: always
    container_name: backend-PRPORTS

  frontend-PRPORTS:
    build:
      context: ./assets
      dockerfile: Dockerfile
    image: nanocloud/frontend
    volumes:
      - static-PRPORTS:/opt/dist
    networks:
      - nanocloud
    container_name: frontend-PRPORTS

  proxy-PRPORTS:
    build: ./proxy
    image: nanocloud/proxy
    ports:
      - PRPORTS:443
    depends_on:
      - backend-PRPORTS
    volumes:
      - ./proxy/nginx.pr.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nanocloud
    restart: always
    container_name: proxy-PRPORTS

  postgres-PRPORTS:
    image: postgres:9.5.3
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=nanocloud
    networks:
      - nanocloud
    restart: always
    container_name: postgres-PRPORTS

  guacamole-client-PRPORTS:
    build: ./guacamole-client
    image: nanocloud/guacamole-client
    networks:
      - nanocloud
    restart: always
    container_name: guacamole-client-PRPORTS

networks:
  nanocloud:
    driver: bridge

volumes:
  static-PRPORTS:
    driver: local
  plaza:
    driver: local
